# yamllint configuration
# Docs: https://yamllint.readthedocs.io/

extends: default

rules:
  line-length:
    max: 120
    level: warning

  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  document-start: disable

  indentation:
    spaces: 2
    indent-sequences: true

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0

ignore:
  - .git/
  - vendor/
  - build/
